[package]
name = "days_dvcs"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
chrono = "0.4.38"
uuid = { version = "1.11.0", features = ["v4"] }
glob = "0.3.1"
